before_script:
    - apt-get --quiet update --yes
    - apt-get --quiet install --yes openjdk-8-jdk ant libhamcrest-java libemma-java

build:
    script:
        - export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
        - ant compileTest dist
        - java -noverify -cp /usr/share/java/emma.jar:build:libtest/*:lib/*:/usr/share/java/hamcrest-all.jar emma run -raw -f -cp build -ix @filters.txt TestRunner
        - java -noverify -cp /usr/share/java/emma.jar emma report -in coverage.es -r html -sp src/
        - cat coverage.txt
        - grep "all classes" coverage.txt | cut -f4
    artifacts:
        paths:
           - dist
           - build
           - coverage
    tags:
        - linux
